-- Sincroniza somente o conteúdo público original, preservando personalizações, IDs, ordem e visibilidade.
SET NAMES utf8mb4;
START TRANSACTION;
UPDATE tb_site_secoes SET titulo_pt='SISTEMAS
CENTRAIS',titulo_en='CORE
SYSTEMS' WHERE chave='services' AND BINARY REPLACE(titulo_pt,CHAR(13),'')='NOSSOS
SERVIÇOS' AND BINARY REPLACE(titulo_en,CHAR(13),'')='OUR
SERVICES' AND BINARY subtitulo_pt <=> 'Especialidades conduzidas por Rodrigo & Fernanda Câmara' AND BINARY subtitulo_en <=> 'Specialty services led by Rodrigo & Fernanda Câmara' AND selo_pt='' AND selo_en='';
UPDATE tb_site_servicos SET imagem_path='assets/rafael-servico-1-b8253284b9a9.jpg' WHERE BINARY titulo_pt <=> 'Paisagismo' AND BINARY titulo_en <=> 'Landscaping' AND BINARY descricao_pt <=> 'Projetos autorais de paisagismo, da concepção 3D à execução final.' AND BINARY descricao_en <=> 'Signature landscape design — from 3D vision to flawless delivery.' AND BINARY imagem_path <=> 'assets/service-landscaping.jpg' AND BINARY icone <=> 'sprout';
UPDATE tb_site_servicos SET imagem_path='assets/rafael-servico-2-4028ff8f2bc1.jpg' WHERE BINARY titulo_pt <=> 'Manutenção' AND BINARY titulo_en <=> 'Maintenance' AND BINARY descricao_pt <=> 'Contratos mensais para condomínios e residências de alto padrão.' AND BINARY descricao_en <=> 'Monthly contracts for premium condominiums and residences.' AND BINARY imagem_path <=> NULL AND BINARY icone <=> 'droplet';
UPDATE tb_site_servicos SET imagem_path='assets/rafael-servico-3-d941886adbc1.jpg' WHERE BINARY titulo_pt <=> 'Poda Técnica' AND BINARY titulo_en <=> 'Expert Pruning' AND BINARY descricao_pt <=> 'Poda de árvores e jardins com técnicas avançadas de condução.' AND BINARY descricao_en <=> 'Tree and garden pruning with advanced shaping techniques.' AND BINARY imagem_path <=> 'assets/service-pruning.jpg' AND BINARY icone <=> 'pruning';
UPDATE tb_site_servicos SET imagem_path='assets/rafael-servico-4-acd84de31fe7.jpg' WHERE BINARY titulo_pt <=> 'Jardinagem' AND BINARY titulo_en <=> 'Gardening' AND BINARY descricao_pt <=> 'Cuidado contínuo, adubação inteligente e saúde vegetal completa.' AND BINARY descricao_en <=> 'Ongoing care, smart fertilization and full plant health.' AND BINARY imagem_path <=> NULL AND BINARY icone <=> 'tree';
UPDATE tb_site_servicos SET imagem_path='assets/rafael-servico-5-03f8ad9d6c5d.jpg' WHERE BINARY titulo_pt <=> 'Comercial' AND BINARY titulo_en <=> 'Commercial' AND BINARY descricao_pt <=> 'Soluções escaláveis para empresas, lobbies e áreas corporativas.' AND BINARY descricao_en <=> 'Scalable solutions for offices, lobbies and corporate sites.' AND BINARY imagem_path <=> 'assets/service-commercial.jpg' AND BINARY icone <=> 'building';
UPDATE tb_site_servicos SET imagem_path='assets/rafael-servico-6-31b0e8a272eb.jpg' WHERE BINARY titulo_pt <=> 'Consultoria' AND BINARY titulo_en <=> 'Consulting' AND BINARY descricao_pt <=> 'Diagnóstico, plano de manejo e curadoria botânica especializada.' AND BINARY descricao_en <=> 'Diagnostics, management plans and curated botanical advisory.' AND BINARY imagem_path <=> NULL AND BINARY icone <=> 'compass';
UPDATE tb_site_projetos SET titulo_pt='Jardim Frontal',categoria_pt='Residencial',imagem_alt_pt='Jardim Frontal',imagem_path='assets/rafael-projeto-1-5076d9ab9003.jpg' WHERE BINARY titulo_pt <=> 'Residência Vista Mar' AND BINARY titulo_en <=> '' AND BINARY descricao_pt <=> '' AND BINARY descricao_en <=> '' AND BINARY categoria_pt <=> 'Residencial' AND BINARY categoria_en <=> '' AND BINARY local <=> '' AND BINARY imagem_path <=> 'assets/gallery-1.jpg' AND BINARY imagem_alt_pt <=> 'Residência Vista Mar' AND BINARY imagem_alt_en <=> '';
UPDATE tb_site_projetos SET titulo_pt='Área de Lazer',categoria_pt='Residencial',imagem_alt_pt='Área de Lazer',imagem_path='assets/rafael-projeto-2-e6bb8b7ca95d.jpg' WHERE BINARY titulo_pt <=> 'Sede Corporativa Atrium' AND BINARY titulo_en <=> '' AND BINARY descricao_pt <=> '' AND BINARY descricao_en <=> '' AND BINARY categoria_pt <=> 'Comercial' AND BINARY categoria_en <=> '' AND BINARY local <=> '' AND BINARY imagem_path <=> 'assets/gallery-2.jpg' AND BINARY imagem_alt_pt <=> 'Sede Corporativa Atrium' AND BINARY imagem_alt_en <=> '';
UPDATE tb_site_projetos SET titulo_pt='Entrada · Parque das Oliveiras',categoria_pt='Condomínio',imagem_alt_pt='Entrada · Parque das Oliveiras',imagem_path='assets/rafael-projeto-3-35bce92e1814.jpg' WHERE BINARY titulo_pt <=> 'Caminho das Palmeiras' AND BINARY titulo_en <=> '' AND BINARY descricao_pt <=> '' AND BINARY descricao_en <=> '' AND BINARY categoria_pt <=> 'Paisagismo' AND BINARY categoria_en <=> '' AND BINARY local <=> '' AND BINARY imagem_path <=> 'assets/gallery-3.jpg' AND BINARY imagem_alt_pt <=> 'Caminho das Palmeiras' AND BINARY imagem_alt_en <=> '';
UPDATE tb_site_projetos SET titulo_pt='Entrada · Villagio Azul',categoria_pt='Condomínio',imagem_alt_pt='Entrada · Villagio Azul',imagem_path='assets/rafael-projeto-4-1ac077b88f0d.jpg' WHERE BINARY titulo_pt <=> 'Condomínio Belvedere' AND BINARY titulo_en <=> '' AND BINARY descricao_pt <=> '' AND BINARY descricao_en <=> '' AND BINARY categoria_pt <=> 'Condomínio' AND BINARY categoria_en <=> '' AND BINARY local <=> '' AND BINARY imagem_path <=> 'assets/gallery-4.jpg' AND BINARY imagem_alt_pt <=> 'Condomínio Belvedere' AND BINARY imagem_alt_en <=> '';
COMMIT;
