<?php
// Definitions describe presentation only; saving remains in each existing route.
function admin_entities() {
    $client = ['TB_Clientes_ID_Cliente','Cliente','select',true,'Dados principais','clients'];
    $order = ['TB_OrdensServico_ID_Ordem','ID da ordem de serviço (opcional)','number',false,'Dados principais'];
    $description = function($name) { return [$name,'Descrição','textarea',false,'Detalhes']; };
    return [
      'clientes'=>['label'=>'Clientes','singular'=>'cliente','icon'=>'users','create'=>'cadastrar_cliente.php','table'=>'tb_clientes','pk'=>'ID_Cliente','edit'=>'id_cliente','editvar'=>'edit_cliente','select'=>'SELECT * FROM tb_clientes','order'=>'ID_Cliente DESC','search'=>['cli_Nome','cli_Email','cli_Telefone','cli_Endereco'],'filter'=>'cli_Tipo','filters'=>['Residencial','Condomínio','Comercial'],
       'fields'=>[['cli_Nome','Nome completo','text',true,'Dados principais','Ex.: Residencial Jardim Aurora'],['cli_Tipo','Tipo de cliente','select',false,'Dados principais',['Residencial','Condomínio','Comercial']],['cli_Telefone','Telefone / WhatsApp','tel',false,'Contato','(19) 99999-9999'],['cli_Email','E-mail','email',false,'Contato','nome@exemplo.com'],['cli_Endereco','Endereço','text',false,'Endereço','Rua, número, bairro e cidade']],
       'columns'=>[['ID_Cliente','ID','id'],['cli_Nome','Nome','strong'],['cli_Tipo','Tipo','badge'],['cli_Telefone','Telefone'],['cli_Email','E-mail'],['cli_Endereco','Endereço']]],
      'produtos'=>['label'=>'Produtos','singular'=>'produto','icon'=>'box','create'=>'cadastrar_produto.php','table'=>'tb_produtos','pk'=>'ID_Produto','edit'=>'id_produto','editvar'=>'edit_produto','select'=>'SELECT * FROM tb_produtos','order'=>'ID_Produto DESC','search'=>['Pro_Nome','Pro_Descricao'],
       'fields'=>[['Pro_Nome','Nome do produto','text',true,'Dados principais','Ex.: Mudas de lavanda'],['Pro_Preco','Preço (R$)','money',true,'Dados principais','0,00'],$description('Pro_Descricao'),['Pro_EstoqueMinimo','Estoque mínimo (opcional)','number',false,'Monitoramento','Deixe vazio para não monitorar','Vazio desativa os alertas. O saldo é calculado pelas entradas e saídas vinculadas ao produto.']],
       'columns'=>[['ID_Produto','ID','id'],['Pro_Nome','Produto','strong'],['Pro_Descricao','Descrição'],['Pro_Preco','Preço','money'],['Pro_EstoqueMinimo','Estoque mínimo']]],
      'servicos'=>['label'=>'Serviços','singular'=>'serviço','icon'=>'leaf','create'=>'cadastrar_servico.php','table'=>'tb_servicos','pk'=>'ID_Servico','edit'=>'id_servico','editvar'=>'edit_servico','select'=>'SELECT * FROM tb_servicos','order'=>'ID_Servico DESC','search'=>['Ser_Nome','Ser_Descricao'],
       'fields'=>[['Ser_Nome','Nome do serviço','text',true,'Dados principais','Ex.: Manutenção de jardim'],['Ser_Preco','Preço (R$)','money',true,'Dados principais','0,00'],$description('Ser_Descricao')],
       'columns'=>[['ID_Servico','ID','id'],['Ser_Nome','Serviço','strong'],['Ser_Descricao','Descrição'],['Ser_Preco','Preço','money']]],
      'fornecedores'=>['label'=>'Fornecedores','singular'=>'fornecedor','icon'=>'truck','create'=>'cadastrar_fornecedor.php','table'=>'tb_fornecedores','pk'=>'ID_Fornecedor','edit'=>'id_fornecedor','editvar'=>'edit_fornecedor','select'=>'SELECT * FROM tb_fornecedores','order'=>'ID_Fornecedor DESC','search'=>['For_Nome','For_Telefone','For_Endereco'],
       'fields'=>[['For_Nome','Nome do fornecedor','text',true,'Dados principais','Ex.: Viveiro Jardim Verde'],['For_Telefone','Telefone','tel',false,'Contato','(19) 99999-9999'],['For_Endereco','Endereço','text',false,'Endereço','Rua, número, bairro e cidade']],
       'columns'=>[['ID_Fornecedor','ID','id'],['For_Nome','Fornecedor','strong'],['For_Telefone','Telefone'],['For_Endereco','Endereço']]],
      'ordens'=>['label'=>'Ordens de serviço','singular'=>'ordem de serviço','icon'=>'clipboard','create'=>'cadastrar_ordem.php','table'=>'tb_ordensservico','pk'=>'ID_Ordem','edit'=>'id_ordem','editvar'=>'edit_ordem','select'=>'SELECT o.*, c.cli_Nome FROM tb_ordensservico o JOIN tb_clientes c ON o.TB_Clientes_ID_Cliente = c.ID_Cliente','order'=>'o.ID_Ordem DESC','search'=>['c.cli_Nome','o.Ord_Observacoes','o.ID_Ordem'],'filter'=>'o.Or_Status','filters'=>['Pendente','Em Andamento','Concluído','Cancelado'],
       'fields'=>[$client,['Or_Status','Status','select',false,'Dados principais',['Em Andamento','Concluído','Cancelado']],['Ord_ValorTotal','Valor total (R$)','money',true,'Dados principais','0,00'],['Ord_Observacoes','Observações','textarea',false,'Detalhes']],
       'columns'=>[['ID_Ordem','Ordem','id'],['cli_Nome','Cliente','strong'],['Ord_DataServico','Data do serviço','date'],['Or_Status','Status','badge'],['Ord_ValorTotal','Valor total','money'],['Ord_Observacoes','Observações']]],
      'agendamentos'=>['label'=>'Agendamentos','singular'=>'agendamento','icon'=>'calendar','create'=>'cadastrar_agendamento.php','table'=>'tb_agendamentos','pk'=>'ID_Agendamento','edit'=>'id_agendamento','editvar'=>'edit_agendamento','select'=>'SELECT a.*, c.cli_Nome FROM tb_agendamentos a JOIN tb_clientes c ON a.TB_Clientes_ID_Cliente = c.ID_Cliente','order'=>'a.Age_DataAgendada DESC','search'=>['c.cli_Nome','a.Age_Observacoes'],'filter'=>'a.Age_Status','filters'=>['Agendado','Realizado','Cancelado'],
       'fields'=>[$client,$order,['Age_DataAgendada','Data e hora agendada','datetime-local',true,'Agendamento'],['Age_Status','Status','select',false,'Agendamento',['Agendado','Realizado','Cancelado']],['Age_Observacoes','Observações','textarea',false,'Detalhes']],
       'columns'=>[['ID_Agendamento','ID','id'],['cli_Nome','Cliente','strong'],['TB_OrdensServico_ID_Ordem','Ordem','id'],['Age_DataAgendada','Data agendada','datetime'],['Age_Status','Status','badge'],['Age_Observacoes','Observações']]],
      'estoque'=>['label'=>'Estoque','singular'=>'movimentação','icon'=>'box','create'=>'cadastrar_estoque.php','table'=>'tb_estoque','pk'=>'ID_Estoque','edit'=>'id_estoque','editvar'=>'edit_estoque','select'=>'SELECT e.*, p.Pro_Nome FROM tb_estoque e LEFT JOIN tb_produtos p ON p.ID_Produto = e.TB_Produtos_ID_Produto','order'=>'e.ID_Estoque DESC','search'=>['e.Est_Tipo','p.Pro_Nome'],'filter'=>'e.Est_Tipo','filters'=>['Entrada','Saida'],
       'fields'=>[['TB_Produtos_ID_Produto','Produto (opcional)','select',false,'Movimentação','products','Vincule um produto para atualizar seu saldo e os alertas.'],['Est_Tipo','Tipo de movimentação','select',true,'Movimentação',['Entrada','Saida']],['Est_Quantidade','Quantidade','number',true,'Movimentação','0']],
       'columns'=>[['ID_Estoque','ID','id'],['Est_Tipo','Tipo','badge'],['Pro_Nome','Produto','strong'],['Est_Quantidade','Quantidade'],['Est_DataMovimentacao','Data da movimentação','datetime']]],
      'financeiro'=>['label'=>'Contas a receber','singular'=>'conta','icon'=>'wallet','create'=>'cadastrar_conta.php','table'=>'tb_contasreceber','pk'=>'ID_ContaReceber','edit'=>'id_conta','editvar'=>'edit_conta','select'=>'SELECT cr.*, c.cli_Nome FROM tb_contasreceber cr JOIN tb_clientes c ON cr.TB_Clientes_ID_Cliente = c.ID_Cliente','order'=>'cr.Con_DataVencimento DESC','search'=>['c.cli_Nome','cr.Con_FormaPagamento','cr.ID_ContaReceber'],'filter'=>'cr.Con_Status','filters'=>['Pendente','Pago','Cancelado','Vencido'],
       'fields'=>[$client,$order,['Con_Valor','Valor (R$)','money',true,'Recebimento','0,00'],['Con_DataVencimento','Data de vencimento','date',true,'Recebimento'],['Con_Status','Status','select',false,'Recebimento',['Pendente','Pago','Cancelado']],['Con_FormaPagamento','Forma de pagamento','text',false,'Recebimento','Pix, cartão, boleto...']],
       'columns'=>[['ID_ContaReceber','ID','id'],['cli_Nome','Cliente','strong'],['TB_OrdensServico_ID_Ordem','Ordem','id'],['Con_Valor','Valor','money'],['Con_DataVencimento','Vencimento','date'],['Con_Status','Status','badge'],['Con_FormaPagamento','Pagamento']]],
      'logins'=>['label'=>'Logins','singular'=>'login','icon'=>'key','create'=>'cadastrar_login.php','table'=>'tb_login','pk'=>'log_codigo','edit'=>'id_login','editvar'=>'edit_login','select'=>'SELECT log_codigo, log_nome, log_login FROM tb_login','order'=>'log_codigo DESC','search'=>['log_nome','log_login'],
       'fields'=>[['log_nome','Nome do usuário','text',true,'Acesso','Ex.: Administrador'],['log_login','Usuário / login','text',true,'Acesso','Nome usado para entrar'],['log_senha','Senha','password',true,'Segurança',null,'Use pelo menos 8 caracteres. Na edição, deixe vazio para manter a senha atual.']],
       'columns'=>[['log_codigo','ID','id'],['log_nome','Usuário','strong'],['log_login','Login']]],
    ];
}
