<?php if (!isset($entity,$key)) { http_response_code(404); exit; } $formVisible = $isCreate || $editing; $title = $isCreate ? 'Cadastrar '.$entity['singular'] : $entity['label']; $newLabel=(in_array($key,['ordens','estoque','financeiro'],true) ? 'Nova ' : 'Novo ').$entity['singular']; ?>
<div class="manage-page">
 <div class="page-heading">
  <div><p class="eyebrow">GOLDEN JARDIM · GESTÃO</p><h1><?= ui_escape($title) ?><span>.</span></h1><p><?= $isCreate ? 'Preencha os dados para adicionar um novo registro.' : 'Consulte e organize os registros da sua operação.' ?></p></div>
  <a class="<?= $isCreate ? 'secondary-action' : 'primary-action' ?>" href="<?= ui_escape($isCreate ? $key.'.php' : $entity['create']) ?>"><?= admin_icon($isCreate ? 'clipboard' : 'plus') ?><?= ui_escape($isCreate ? 'Ver existentes' : $newLabel) ?></a>
 </div>
 <nav class="page-breadcrumb" aria-label="Caminho da página"><a href="dashboard.php">Painel</a><span>/</span><a href="<?= ui_escape($key.'.php') ?>"><?= ui_escape($entity['label']) ?></a><span>/</span><span aria-current="page"><?= $isCreate ? 'Cadastrar' : ($editing ? 'Editar' : 'Consultar') ?></span></nav>
 <?php if ($message && ($_SERVER['REQUEST_METHOD'] ?? 'GET') !== 'POST'): ?><div class="feedback feedback-success" role="status"><?= admin_icon('check') ?><span><?= ui_escape($message) ?></span></div><?php endif; ?>
 <?php if ($error || !empty($GLOBALS['admin_form_errors'])): ?><div class="feedback feedback-error" role="alert"><?= admin_icon('alert') ?><div><strong>Não foi possível salvar a alteração.</strong><p><?= ui_escape($error ?: implode(' ',array_unique($GLOBALS['admin_form_errors']))) ?></p></div></div><?php endif; ?>
 <?php if (!$isCreate && isset($_GET['acao']) && $_GET['acao']==='editar' && !$editing): ?><div class="feedback feedback-error" role="alert">Registro não encontrado. Escolha um registro da lista.</div><?php endif; ?>
 <?php if ($formVisible) include __DIR__ . '/manage_form.php'; ?>
 <?php if (!$isCreate): ?>
 <?php if ($key === 'estoque'): $stock = dashboard_stock($con); ?>
 <section class="manage-card stock-overview" aria-label="Estoque em alerta"><div class="card-heading"><div><h2>Estoque em alerta</h2><p>Saldo atual e mínimos configurados por produto.</p></div><span class="count-pill"><?= count($stock['alerts']) ?> alertas</span></div>
 <?php if (!$stock['alerts']): ?><p class="stock-empty">Nenhum produto em alerta no momento.</p><?php else: ?><div class="stock-overview-grid"><?php foreach ($stock['alerts'] as $alert): ?><div class="stock-item"><div><strong><?= ui_escape($alert['Pro_Nome']) ?></strong><?= ui_badge($alert['critical'] ? 'Crítico' : 'Baixo') ?></div><progress class="<?= $alert['critical'] ? 'danger' : 'warning' ?>" max="100" value="<?= ui_escape($alert['progress']) ?>" aria-label="<?= ui_escape('Nível de estoque de '.$alert['Pro_Nome']) ?>"></progress><small><?= ui_escape($alert['saldo']) ?> em estoque <span>Mínimo: <?= ui_escape($alert['minimo']) ?></span></small></div><?php endforeach; ?></div><?php endif; ?></section>
 <?php endif; ?>
 <section class="manage-card list-card" aria-label="<?= ui_escape('Lista de '.$entity['label']) ?>">
  <div class="card-heading"><div><h2><?= ui_escape($entity['label']) ?></h2><p><?= (int)$data['all'] ?> <?= ui_escape($key==='estoque' ? 'movimentações' : mb_strtolower($entity['label'],'UTF-8')) ?> no sistema</p></div><span class="count-pill"><?= (int)$data['total'] ?> <?= $data['total']===1 ? 'registro' : 'registros' ?></span></div>
  <form action="<?= ui_escape($key.'.php') ?>" method="GET" class="list-toolbar"><div class="list-search"><label for="listSearch" class="sr-only">Buscar registros</label><?= admin_icon('search') ?><input type="search" id="listSearch" name="q" value="<?= ui_escape($data['q']) ?>" placeholder="Buscar <?= ui_escape(mb_strtolower($entity['label'],'UTF-8')) ?>..."></div>
   <?php if (!empty($entity['filters'])): ?><label class="sr-only" for="listFilter">Filtrar por tipo ou status</label><select name="filtro" id="listFilter"><option value="">Todos os <?= $key==='clientes' || $key==='estoque' ? 'tipos' : 'status' ?></option><?php foreach ($entity['filters'] as $filter): ?><option value="<?= ui_escape($filter) ?>" <?= $data['filter']===$filter ? 'selected' : '' ?>><?= ui_escape($filter==='Saida' ? 'Saída' : $filter) ?></option><?php endforeach; ?></select><?php endif; ?>
   <button class="secondary-action" type="submit">Filtrar</button><?php if ($data['q']!=='' || $data['filter']!==''): ?><a class="text-action" href="<?= ui_escape($key.'.php') ?>">Limpar</a><?php endif; ?>
  </form>
  <?php if (!$data['rows']): ?><div class="empty-state"><?= admin_icon($entity['icon']) ?><strong><?= $data['all'] ? 'Nenhum resultado encontrado' : 'Sua lista começa aqui' ?></strong><p><?= $data['all'] ? 'Tente outro termo ou remova os filtros.' : 'Adicione o primeiro registro para começar a organizar sua operação.' ?></p><a class="primary-action" href="<?= ui_escape($entity['create']) ?>"><?= admin_icon('plus') ?>Novo cadastro</a></div>
  <?php else: ?><div class="table-scroll" tabindex="0" role="region" aria-label="Tabela de registros; deslize para ver todas as colunas"><table class="manage-table"><thead><tr><?php foreach ($entity['columns'] as $column): ?><th scope="col"><?= ui_escape($column[1]) ?></th><?php endforeach; ?><th scope="col">Ações</th></tr></thead><tbody>
  <?php foreach ($data['rows'] as $row): ?><tr><?php foreach ($entity['columns'] as $column): $value=$row[$column[0]] ?? null; $kind=$column[2] ?? ''; ?><td class="<?= $kind==='id' ? 'record-id' : ($kind==='strong' ? 'record-title' : 'record-secondary') ?>"><?php
   if ($value === null || $value === '') echo '—';
   elseif ($kind==='badge') { if ($key==='financeiro' && $value==='Pendente' && $row['Con_DataVencimento'] < ui_today()) $value='Vencido'; echo ui_badge($value); }
   elseif ($kind==='money') echo ui_escape('R$ '.number_format((float)$value,2,',','.'));
   elseif ($kind==='date' || $kind==='datetime') echo ui_escape(strtotime($value) ? date($kind==='date' ? 'd/m/Y' : 'd/m/Y H:i',strtotime($value)) : '—');
   else echo ui_escape(($kind==='id' ? '#' : '').$value);
  ?></td><?php endforeach; ?><td><div class="row-actions"><a class="icon-button" title="Editar registro" aria-label="<?= ui_escape('Editar registro '.$row[$entity['pk']]) ?>" href="<?= ui_escape(ui_link(['acao'=>'editar','id'=>$row[$entity['pk']],'q'=>$data['q'],'filtro'=>$data['filter'],'pagina'=>$data['page']])) ?>"><?= admin_icon('edit') ?></a>
  <?php $protected = $key==='logins' && (strcasecmp(trim($row['log_login']),'Adm')===0 || (int)$row['log_codigo']===(int)$_SESSION['log_codigo'] || $data['all']<=1); if ($protected): ?><span class="icon-button protected-record" title="Acesso protegido" aria-label="Acesso protegido"><?= admin_icon('lock') ?></span><?php else: ?><form method="POST" action="<?= ui_escape($key.'.php') ?>" data-delete-form data-confirm-msg="<?= ui_escape('Excluir este registro de '.$entity['singular'].'?') ?>"><?= csrf_field() ?><input type="hidden" name="acao" value="excluir"><input type="hidden" name="id" value="<?= ui_escape($row[$entity['pk']]) ?>"><button class="icon-button delete-action" type="submit" title="Excluir registro" aria-label="<?= ui_escape('Excluir registro '.$row[$entity['pk']]) ?>"><?= admin_icon('trash') ?></button></form><?php endif; ?></div></td></tr><?php endforeach; ?>
  </tbody></table></div><?php endif; ?>
  <nav class="list-pagination" aria-label="Paginação"><span><?= $data['total'] ? (($data['page']-1)*10+1).'–'.min($data['page']*10,$data['total']) : '0' ?> de <?= (int)$data['total'] ?> registros</span><div><?php foreach (['Anterior'=>max(1,$data['page']-1),'Próxima'=>min($data['pages'],$data['page']+1)] as $label=>$page): if ($page===$data['page']): ?><span class="pagination-disabled" aria-disabled="true"><?= ui_escape($label) ?></span><?php else: ?><a class="secondary-action" href="<?= ui_escape(ui_link(['q'=>$data['q'],'filtro'=>$data['filter'],'pagina'=>$page])) ?>"><?= ui_escape($label) ?></a><?php endif; if ($label==='Anterior'): ?><span>Página <?= (int)$data['page'] ?> de <?= (int)$data['pages'] ?></span><?php endif; endforeach; ?></div></nav>
 </section><?php endif; ?>
</div>
