<?php require_once dirname(__DIR__).'/bootstrap.php'; require_login(); exigirPermissao('conteudo_publico'); if (!isset($site_config,$site_rows)) { http_response_code(404); exit; } $route=$site_config['route']; $editing=(bool)$site_id; $public='../index.php#'.$site_config['section']; ?>
<div class="manage-page site-manage-page">
 <div class="page-heading"><div><p class="eyebrow">GOLDEN JARDIM · SITE</p><h1><?= ui_escape($site_form ? ($editing ? 'Editar ' : 'Novo ').$site_config['singular'] : $site_config['label']) ?><span>.</span></h1><p>Organize o conteúdo que seus visitantes veem no site.</p></div><a class="<?= $site_form ? 'secondary-action' : 'primary-action' ?>" href="<?= ui_escape($route.($site_form ? '' : '?acao=novo')) ?>"><?= admin_icon($site_form ? 'clipboard' : 'plus') ?><?= $site_form ? 'Ver existentes' : ui_escape('Novo '.$site_config['singular']) ?></a></div>
 <nav class="page-breadcrumb" aria-label="Caminho da página"><a href="dashboard.php">Painel</a><span>/</span><span>Site</span><span>/</span><a href="<?= ui_escape($route) ?>"><?= ui_escape($site_config['label']) ?></a><span>/</span><span aria-current="page"><?= $site_form ? ($editing ? 'Editar' : 'Cadastrar') : 'Consultar' ?></span></nav>
 <?php if ($site_flash): ?><div class="feedback <?= $site_flash['warning'] ? 'feedback-error' : 'feedback-success' ?> site-toast" role="status"><?= admin_icon($site_flash['warning'] ? 'alert' : 'check') ?><div><strong><?= ui_escape($site_flash['text']) ?></strong><a href="<?= ui_escape($public) ?>" target="_blank" rel="noopener">Ver no site <?= admin_icon('arrow') ?></a></div><button class="icon-button" type="button" data-close-toast aria-label="Fechar aviso"><?= admin_icon('close') ?></button></div><?php endif; ?>
 <?php if ($site_error): ?><div class="feedback feedback-error" role="alert"><?= admin_icon('alert') ?><div><strong>Confira a alteração.</strong><p><?= ui_escape($site_error) ?></p></div></div><?php endif; ?>
 <?php if ($site_form): require __DIR__.'/site_form.php'; else: ?>
 <section class="manage-card"><div class="card-heading"><div><h2><?= ui_escape($site_config['label']) ?></h2><p><?= count($site_rows) ?> cadastrados · <?= count(array_filter($site_rows,fn($row)=>(int)$row['ativo']===1)) ?> ativos no site</p></div><a class="secondary-action" href="<?= ui_escape($public) ?>" target="_blank" rel="noopener">Ver no site <?= admin_icon('arrow') ?></a></div>
 <?php if (!$site_rows): ?><div class="empty-state"><?= admin_icon($site_config['icon']) ?><strong>Comece a contar sua história</strong><p>Cadastre o primeiro <?= ui_escape($site_config['singular']) ?>. Enquanto a tabela estiver vazia, o site mostra o conteúdo original.</p><a class="primary-action" href="<?= ui_escape($route.'?acao=novo') ?>">Novo <?= ui_escape($site_config['singular']) ?></a></div>
 <?php else: ?><div class="table-scroll" tabindex="0" role="region" aria-label="Tabela de conteúdo; deslize para ver todas as colunas"><table class="manage-table site-table"><thead><tr><th scope="col">Imagem</th><th scope="col">Conteúdo</th><th scope="col">Ordem</th><th scope="col">Visibilidade</th><th scope="col">Ações</th></tr></thead><tbody>
 <?php foreach ($site_rows as $position=>$row): $image=site_image_path($row['imagem_path']); ?><tr>
  <td class="site-thumb-cell"><?php if ($image): ?><img class="site-thumb" src="<?= ui_escape('../'.$image) ?>" alt="" loading="lazy"><?php else: ?><span class="site-thumb site-thumb-empty" aria-label="Sem imagem"><?= admin_icon('image') ?></span><?php endif; ?></td>
  <td><strong class="record-title"><?= ui_escape($row['titulo_pt']) ?></strong><small class="site-record-description"><?= ui_escape(mb_strimwidth($row['descricao_pt'],0,100,'…','UTF-8')) ?></small><small class="record-secondary"><?= trim($row['titulo_en'])==='' ? 'EN usa o título em português' : ui_escape('EN: '.$row['titulo_en']) ?></small></td>
  <td><div class="row-actions"><span class="record-id"><?= (int)$row['ordem'] ?></span><?php foreach (['subir'=>['up','Mover para cima',$position===0],'descer'=>['down','Mover para baixo',$position===count($site_rows)-1]] as $action=>$button): ?><form method="POST" action="<?= ui_escape($route) ?>"><?= csrf_field() ?><input type="hidden" name="acao" value="<?= ui_escape($action) ?>"><input type="hidden" name="registro" value="<?= (int)$row['id'] ?>"><button class="icon-button" type="submit" aria-label="<?= ui_escape($button[1].': '.$row['titulo_pt']) ?>" <?= $button[2] ? 'disabled' : '' ?>><?= admin_icon($button[0]) ?></button></form><?php endforeach; ?></div></td>
  <td><form method="POST" action="<?= ui_escape($route) ?>"><?= csrf_field() ?><input type="hidden" name="acao" value="alternar"><input type="hidden" name="registro" value="<?= (int)$row['id'] ?>"><button class="site-toggle" type="submit" role="switch" aria-checked="<?= (int)$row['ativo']===1 ? 'true' : 'false' ?>" aria-label="<?= ui_escape('Visibilidade de '.$row['titulo_pt']) ?>"><span class="site-switch-track" aria-hidden="true"></span><span class="status-badge <?= (int)$row['ativo']===1 ? 'success' : 'neutral' ?>"><?= (int)$row['ativo']===1 ? 'Ativo' : 'Inativo' ?></span></button></form></td>
  <td><div class="row-actions"><a class="icon-button" href="<?= ui_escape($route.'?acao=editar&id='.$row['id']) ?>" aria-label="<?= ui_escape('Editar '.$row['titulo_pt']) ?>"><?= admin_icon('edit') ?></a><form method="POST" action="<?= ui_escape($route) ?>" data-delete-form data-confirm-msg="<?= ui_escape('Excluir “'.$row['titulo_pt'].'”? A imagem enviada também será removida, se não estiver em uso por outro card.') ?>"><?= csrf_field() ?><input type="hidden" name="acao" value="excluir"><input type="hidden" name="registro" value="<?= (int)$row['id'] ?>"><button class="icon-button delete-action" type="submit" aria-label="<?= ui_escape('Excluir '.$row['titulo_pt']) ?>"><?= admin_icon('trash') ?></button></form></div></td>
 </tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>
 <p class="field-help">Use as setas para organizar a exibição. Cards inativos ficam ocultos. Alterações aparecem no site ao atualizar a página.</p>
 <?php endif; ?>
</div>
