<?php require_once dirname(__DIR__).'/bootstrap.php'; require_login(); exigirPermissao('conteudo_publico'); if (!isset($site_config,$site_values)) { http_response_code(404); exit; } ?>
<section class="manage-card form-card site-form-card"><div class="card-heading"><div><h2><?= $editing ? 'Dados do '.$site_config['singular'] : 'Conteúdo do novo '.$site_config['singular'] ?></h2><p>Inglês é opcional. Campos vazios usam o texto em português.</p></div><?= admin_icon($site_config['icon']) ?></div>
 <form class="manage-form" data-site-form method="POST" enctype="multipart/form-data" action="<?= ui_escape($route) ?>" novalidate>
 <?= csrf_field() ?><input type="hidden" name="acao" value="salvar"><input type="hidden" name="registro" value="<?= $site_id ?: '' ?>"><input type="hidden" name="MAX_FILE_SIZE" value="5242880">
 <fieldset><legend>Textos em português e inglês</legend><div class="form-grid">
 <?php foreach ($site_config['fields'] as $name=>$field): if ($name==='icone') continue; $value=$site_values[$name] ?? ''; $error=$site_errors[$name] ?? ''; ?>
 <div class="form-field <?= $name==='local' ? 'field-wide' : '' ?>"><label for="site-<?= ui_escape($name) ?>"><?= ui_escape($field[0]) ?><?= $field[2] ? ' <span class="required-mark">*</span>' : '' ?></label>
 <?php $attributes=' id="site-'.ui_escape($name).'" name="'.ui_escape($name).'" maxlength="'.(int)$field[3].'" data-char-count aria-describedby="site-'.ui_escape($name).'-count site-'.ui_escape($name).'-error" aria-invalid="'.($error ? 'true' : 'false').'"'.($field[2] ? ' required' : ''); if ($field[1]==='textarea'): ?><textarea<?= $attributes ?> rows="3"><?= ui_escape($value) ?></textarea><?php else: ?><input<?= $attributes ?> type="text" value="<?= ui_escape($value) ?>"><?php endif; ?>
 <div class="site-field-meta"><small class="field-help" id="site-<?= ui_escape($name) ?>-count"><?= mb_strlen((string)$value,'UTF-8') ?> / <?= (int)$field[3] ?></small></div><p class="field-error" id="site-<?= ui_escape($name) ?>-error" aria-live="polite"><?= ui_escape($error) ?></p></div>
 <?php endforeach; ?></div></fieldset>
 <fieldset><legend>Imagem principal</legend><div class="site-image-grid"><div class="form-field"><label for="site-imagem">Imagem de fundo</label><input type="file" id="site-imagem" name="imagem" accept="image/jpeg,image/png,image/webp" aria-describedby="site-imagem-help site-imagem-error" aria-invalid="<?= isset($site_errors['imagem']) ? 'true' : 'false' ?>"><p class="field-help" id="site-imagem-help">JPG, PNG ou WebP · até 5 MB. Proporção recomendada: 4:5 (ex.: 1200 × 1500 px). O servidor otimiza a imagem para até 1600 px de largura.</p><p class="field-help">Para manter a imagem atual, deixe este campo vazio. Sem imagem, o site utiliza o fundo verde do card.</p><p class="field-error" id="site-imagem-error" aria-live="polite"><?= ui_escape($site_errors['imagem'] ?? '') ?></p></div>
 <div class="site-preview" id="siteImagePreview"><?php $preview=site_image_path($site_record['imagem_path'] ?? null); ?><img id="sitePreviewImage" alt="Pré-visualização da imagem" <?= $preview ? 'src="'.ui_escape('../'.$preview).'"' : 'hidden' ?>><span id="sitePreviewEmpty" <?= $preview ? 'hidden' : '' ?>><?= admin_icon('image') ?>Pré-visualização da imagem</span></div></div></fieldset>
 <fieldset><legend>Exibição no site</legend><div class="form-grid">
 <?php if ($site_kind==='services'): ?><div class="form-field"><label for="site-icone">Ícone <span class="required-mark">*</span></label><select id="site-icone" name="icone" required aria-describedby="site-icone-error" aria-invalid="<?= isset($site_errors['icone']) ? 'true' : 'false' ?>"><?php foreach ($site_config['icons'] as $value=>$label): ?><option value="<?= ui_escape($value) ?>" <?= ($site_values['icone'] ?? '')===$value ? 'selected' : '' ?>><?= ui_escape($label) ?></option><?php endforeach; ?></select><p class="field-error" id="site-icone-error" aria-live="polite"><?= ui_escape($site_errors['icone'] ?? '') ?></p></div><?php endif; ?>
 <div class="form-field"><label for="site-ordem">Ordem <span class="required-mark">*</span></label><input type="number" id="site-ordem" name="ordem" min="0" max="9999" step="1" required value="<?= ui_escape($site_values['ordem'] ?? 0) ?>" aria-describedby="site-ordem-help site-ordem-error" aria-invalid="<?= isset($site_errors['ordem']) ? 'true' : 'false' ?>"><p class="field-help" id="site-ordem-help">Menores números aparecem primeiro. Empates seguem a ordem de cadastro.</p><p class="field-error" id="site-ordem-error" aria-live="polite"><?= ui_escape($site_errors['ordem'] ?? '') ?></p></div>
 <div class="form-field"><label for="site-ativo">Visibilidade <span class="required-mark">*</span></label><select id="site-ativo" name="ativo" required aria-describedby="site-ativo-error"><option value="1" <?= (string)($site_values['ativo'] ?? '')==='1' ? 'selected' : '' ?>>Ativo — aparece no site</option><option value="0" <?= (string)($site_values['ativo'] ?? '')==='0' ? 'selected' : '' ?>>Inativo — oculto no site</option></select><p class="field-error" id="site-ativo-error" aria-live="polite"><?= ui_escape($site_errors['ativo'] ?? '') ?></p></div></div></fieldset>
 <div class="form-actions"><button class="primary-action" type="submit"><?= admin_icon('check') ?>Salvar <?= ui_escape($site_config['singular']) ?></button><a class="secondary-action" href="<?= ui_escape($public) ?>" target="_blank" rel="noopener">Ver no site <?= admin_icon('arrow') ?></a><a class="text-action" href="<?= ui_escape($route) ?>">Cancelar</a></div>
 </form>
</section>
